package com.freebills.gateways.entities.enums;

public enum EventType {

    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,
    TRANSACTION_TRANSFER,

    ACCOUNT_CREATED,
    ACCOUNT_DELETED,

    TRANSFER_CREATED,
    TRANSFER_DELETED,
    TRANSFER_UPDATED

}